[toolchain]
channel="1.88.0"

targets = [ 
  # "x86_64-unknown-linux-musl", 
  # "aarch64-unknown-linux-musl", 
  # "x86_64-pc-windows-msvc" 
  # "aarch64-pc-windows-msvc" 
  # "x86_64-apple-darwin",
  # "aarch64-apple-darwin" 
]
components = [
"cargo",
"clippy",
"rust-std",
"rustc",
"rustfmt",

"rust-analyzer", 
"rust-src", 
]
